category_service and initial infrastructure
Ilya-Dubenok/project_1c pull request #1
Opened 2023-10-25 17:38 UTC by Ilya-Dubenok

2023-10-27 15:15 UTC, Avokado-an requested changes

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/enpoint/web/handler/ControllersExceptionHandler.java
> +
лайн брейки

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +@Validated
валидацию дто проводи в контроллере, это его работа проверять request от пользователя, а тут уже работай с дто, которые точно правильные

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +@AllArgsConstructor
делай бины финальными и requiredArgsConstructor юзай

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +    public Category save(CategoryCreateDTO categoryCreateDTO) {
разбей этот метод на подметоы. В идеале пара вызовов методов для валидации данных, которые в случае неправильного выполнения кидают эксепшн, а потом просто вызов репозитория и маппинг значений

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +        Category toPersist = new Category(UUID.randomUUID(), categoryName, parent, rules);
не очень имя для переменной

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +        return categoryRepository.findById(uuid).orElse(null);
налл не возвращй тут. Лучше кидай соответствующий эксепшн
ну а еще не возвращай объекты слоя базы в контроллер. Делай отдельный дто для этого, с которым будет работать твой сервис и возвращать

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +@Service
обзий коммент, не возвращай в контроллер объекты из базы, возвращай дто

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +        if (currentRequestedPage < 0 || rowsPerPage < 1) {
получай из контроллера pageable напрямую, чтобы не делать лишнюю валидацию и маппинг, намного лаконичнее будет

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +                PageRequest.of(currentRequestedPage,rowsPerPage, Sort.by("name"))
и весь этот пейдж реквест будет простым объектом из контроллера. Погугли, там оч легко и лаконично

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +        toUpdate.setName(categoryUpdateDTO.getName());
лучше не исопльзуй такого типажа имена, даже categoryToUpdate намного лучше, тк тут не сразу ясно, что ты вообще апдейтить хочешь, если бегло код смотреть

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +    public void delete(UUID uuid) {
лищние лайн брейки

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +            return null;
не возвращай наллы, это общая рекомендация, тк нал поинтер никогда никого не делал счастливее. Либо эксепшены, либо полноценные значения

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +        for (RuleCreateDTO ruleCreateDTO : rules) {
перепиши этот метод, чтобы использовать стримы, стандартные циклы выглядят сильно менее красиво и лаконично

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/CategoryService.java
> +            if (ruleCreateDTO instanceof QuantityRuleCreateDTO) {
инстанс оф - опасная штука. Как только у тебя будут появляться новые рулы, твой метод будет дико раздуваться. Подумай как переделать это так, чтобы более расширяемый был код. Если будут с этим сложности, напиши мне и вместе подумаем

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/api/ICategoryService.java
> +    Category save(@Valid CategoryCreateDTO categoryCreateDTO);
@valid вставь в уровень контроллеров, а не в уровень сервисов

2023-10-27 15:15 UTC, Avokado-an commented on category_service/src/main/java/org/example/service/api/ICategoryService.java
> +    Category findByUUID(UUID uuid);
еще раз напомню, что нигде из контроллеров не возвращай классы уровня базы данных

2023-10-28 13:13 UTC, Ilya-Dubenok commented on shared/src/main/java/org/example/entities/QuantityRule.java
> +    public RuleType getRuleType() {
да, дает, уберу в соответствующих местах

2023-10-28 19:46 UTC, Ilya-Dubenok commented on category_service/src/main/java/org/example/service/CategoryService.java
> +        for (RuleCreateDTO ruleCreateDTO : rules) {
переписал, но не уверен, что получилось намного лучше. можешь глянуть еще раз?

2023-10-28 19:51 UTC, Ilya-Dubenok commented on category_service/src/main/java/org/example/service/CategoryService.java
> +            if (ruleCreateDTO instanceof QuantityRuleCreateDTO) {
изменил логику, перенес ее в modelmapper. но тоже не уверен, что это спасет от раздувания кода. Можешь посмотреть?
[ссылка на modelmapper коммит](https://github.com/Ilya-Dubenok/project_1c/commit/1a50076bb5c4255a731237aa1a3c858e11a2e980#diff-9cf1713f32b2111d2ee4970f8c4cab42fa93a7e4c91ba1d2c10340991bc14bfcR34-R52)

2023-10-28 19:59 UTC, Ilya-Dubenok commented on category_service/src/main/java/org/example/enpoint/web/handler/ControllersExceptionHandler.java
> +public class ControllersExceptionHandler extends ResponseEntityExceptionHandler {
посмотрел, у меня ControllersExceptionHandler делает дополнительную логику только для трех типов ошибок: ConstraintViolationException, MethodArgumentNotValidException и DataIntegrityViolationException.
Первые два я не могу словить (или не нашел, как их словить правильно). Последний тип может возникнуть в любом месте обращения сервиса к репозиторию. Т.е. мне нужно в почти каждом методе сервиса прописывать try-catch и делать маппинг? Или есть другой подход, которого я не вижу?

2023-10-28 20:48 UTC, Ilya-Dubenok commented on shared/src/main/java/org/example/dto/rule/ExpirationRuleCreateDTO.java
> +    @JsonProperty("days_till_expiration")
писал для spring-doc-openapi, т.к. он не читает в snake_case без доп. настроек. нашел сейчас эти настройки и убрал ненужное

2023-10-29 09:59 UTC, Ilya-Dubenok commented on shared/src/main/java/org/example/dto/rule/RuleCreateDTO.java
> +
для того, чтобы на контроллере я мог принимать CategoryCreateDTO с[ List\<RuleCreateDTO\>](https://github.com/Ilya-Dubenok/project_1c/blob/2e3a0f764d674dd1c99c350574585d2246a558de/category_service/src/main/java/org/example/core/dto/category/CategoryCreateDTO.java#L24C1-L24C1). Все имплементации RuleCreateDTO наследуются от него, но т.к. при стандартной десериализации нельзя определить, какая именно реализация RuleCreateDTO нужна ([ExpirationRuleCreateDTO](https://github.com/Ilya-Dubenok/project_1c/blob/2e3a0f764d674dd1c99c350574585d2246a558de/category_service/src/main/java/org/example/core/dto/rule/ExpirationRuleCreateDTO.java#L13) или [QuantityRuleCreateDTO](https://github.com/Ilya-Dubenok/project_1c/blob/2e3a0f764d674dd1c99c350574585d2246a558de/category_service/src/main/java/org/example/core/dto/rule/QuantityRuleCreateDTO.java#L13)), необходим данный класс-модель, аннотации над ним и определяют правила маппинга к конкретному полю

2023-10-29 10:21 UTC, Ilya-Dubenok commented on category_service/src/main/java/org/example/dao/entities/Category.java
> +    private List<IRule> rules;
Это решение, которое я нашел для того, чтобы можно было сохранять в бд и доставать из нее интерфейсы. Я сначала решил, что сущность **Правило** является скорее интерфейсом, чем абстрактным классом. И для того, чтобы правильно определять, какая именно имплементация интерфейса достается из бд, необходимо определить логику этого маппинга. В данном случае в бд под каждую реализацию интерфейса создается 
своя таблица (expiration_rule и quantity_rule), каждая со своими уникальными полями. Дополнительно создается  кросс-таблица ("categories_rules"), где хранятся 1)category_id, 2)rule_id 3)rule_type (text).
Поле **rule_type** хранит в себе **discriminator** (заданный приложением), к примеру, Q или E. Если значение Q,  значит при чтении из бд берется rule_id и ищется в таблице quantity_rule, на основе записи формируется QuantityRule. Если Е, то в expiration_rule, и формируется ExpirationRule. 

@ManyToAny - аннотация, которая говорит, что тут может быть несколько типов данных (таблиц)
@AnyDiscriminator - каким будет дискриминатор для определения конкретного типа данных
@AnyDiscriminatorValue - правила маппинга, в данном случае по стринговому дискриминатору "E" мапится ExpirationRule.class, по "Q" - QuantityRule.class

2023-10-30 18:58 UTC, Ilya-Dubenok commented on category_service/src/main/java/org/example/service/CategoryService.java
> +        for (RuleCreateDTO ruleCreateDTO : rules) {
нашел способ покрасивше, но все равно глянь, пожалуйста)
[коммит](https://github.com/Ilya-Dubenok/project_1c/pull/1/commits/6c80f7b851c4ca58cfa062f184cc8b95e8a59eb1#diff-da042410612f2556ce78edc66c8389e5766a96bc0307baa1d46a9f205c4e7c10R111)

2023-11-08 14:42 UTC, Avokado-an commented on category_service/src/main/java/org/example/core/exception/CategoryNotFoundException.java
> +public class CategoryNotFoundException extends RuntimeException {
лучше сделай нейминг общий для приложения (энтити нот фаунд эксепшн например), чтобы ты его в различных ситуациях мог использоваться, притом логика сохраняется

2023-11-08 14:42 UTC, Avokado-an commented on category_service/src/main/java/org/example/dao/entities/Category.java
> +    private List<IRule> rules;
хмммм, ну хорошо, допустим так. Интересный кейс тут с маппингом к нескольким таблицам одного интерфейса сразу, любопытно

2023-11-08 14:42 UTC, Avokado-an commented on category_service/src/main/java/org/example/enpoint/web/handler/ControllersExceptionHandler.java
> +public class ControllersExceptionHandler extends ResponseEntityExceptionHandler {
секундочку, если ты просто настроишь эксепшн хендлер на ловлю ConstraintViolationException он у тебя его игнорит и выдаёт не обработанную ошибку или как именно происходит? Тк я видел, что у тебя отдельно настроен маппинг сообщений для constratintValidationException, что по идее тебе как раз даёт удобный способ обработки ошибок (ловишь в экспешн хендлере -> выкидываешь респонс энтити с сообщением из ошибки)

2023-11-08 17:04 UTC, Ilya-Dubenok commented on category_service/src/main/java/org/example/enpoint/web/handler/ControllersExceptionHandler.java
> +public class ControllersExceptionHandler extends ResponseEntityExceptionHandler {
не совсем правильно выразился. чтобы не путаться, я перепроверил и вижу, что ConstraintViolationException у меня сейчас в приложении не выкидывается, я уберу его из кода. 
что касается MethodArgumentNotValidException, то она в моем случае срабатывает в момент, когда запросом вызывается какой-то метод контроллера, в который передаются невалидные аргументы. Под "не могу словить" я имел в виду, что эта ошибка выкидывается до начала выполнения написанного мной кода, то есть я не могу словить ее именно в методе контроллера. Поэтому, чтобы вернуть как-то обработанную ошибку, пришлось ее обрабатывать на эксепшн хендлере. А обрабатывать нужно, т.к. стандартный месседж из из ошибки слишком подробный, а тут хотелось бы возвращать только суть.

2023-11-09 07:27 UTC, merged